
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - app2scale.scop.tr.asseco-see.local
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app2scale.scop.tr.asseco-see.local
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - app2scale.scop.tr.asseco-see.local
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
